### ISSUE TITLE
Password field type

### ISSUE THREAD

**Issue by sizzlemctwizzle** [sizzlemctwizzle/GM_config#48]
Add a field type for password input. Not sure this is great idea because of the false sense of security it could give someone.

**Comment by Destroy666x** [comment]
> Unless you want to add a non-reversible encryption which will run into U.S. export laws I recommend against this since you are correct it will give a false sense of security. localStorage is rumored to shared with the host site as well so those using this library under those platforms would have access to sensitive information.

This is honestly such a horrible reasoning considering `input` with `password` type exists in HTML and can be used by devs for any purpose whatsover, e.g. a field that could be displayed with 50 size font on the next screen. What makes this any different? Absolutely nothing. It's up for devs to make it clear to users as to how safe the data is.

Also, now I'll instead blame you for accidentally leaking something instead, as I coded a browser script a year ago, forgot there was no sensitive data handling in this plugin after coming back to it now and showed something on my stream I shouldn't have, luckily not too important and changeable. If there was a masked input, I'd instantly use it, instead of delaying wasting time on manually adding such basic feature.
