### ISSUE TITLE
The functions open/close/save/reset throw errors when called indirectly

### ISSUE THREAD

**Issue by wilcooo** [sizzlemctwizzle/GM_config#93]
### To recreate

    GM_config.init( {id:"0"} )

    document.onclick = GM_config.open

_And then click the document_

### What goes wrong

I get the following error: `TypeError: this.create is not a function`  
This is because `this` now isn't the `GM_config` instance, but rather the `document`. The `close`, `reset` and `save` functions have the same problem, with `save` even deleting the full `document.innerHTML`. There may very well be more functions, I haven't done much more research.

This doesn't only form a problem in the above scenario, but also when passing one of those problematic functions as callbacks to all sorts of other native- or library Javascript code; for example `setTimeout( GM_config.open, 1000 )`

### Workaround

Use `document.onclick = ()=>GM_config.open()` or `setTimeout( ()=>GM_config.open(), 1000 )` etc.

**Comment by sizzlemctwizzle** [comment]
This is a known issue and part of OOP in JS. Normally you just warp the call to the method in an anonymous function (or now using lambda syntax like you did). This is some issue that exclusive to GMC. I've considered making some the method more modular so that they call be passed around. Atm it's not something I have plans to pursue.
